name: OCPP Proxy
version: '0.1.0'
slug: ocpp-proxy
description: 'OCPP 1.6 JSON WebSocket proxy for EV charger sharing'
homeassistant_api: true
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
startup: services
boot: auto
options:
  allow_shared_charging: true
  preferred_provider: ''
  blocked_providers: []
  allowed_providers: []
  presence_sensor: ''
  override_input_boolean: ''
  rate_limit_seconds: 10
  ocpp_services: []
schema:
  allow_shared_charging:
    type: boolean
  preferred_provider:
    type: string
  blocked_providers:
    type: array
    items:
      type: string
  allowed_providers:
    type: array
    items:
      type: string
  presence_sensor:
    type: string
  override_input_boolean:
    type: string
  rate_limit_seconds:
    type: integer
  ocpp_services:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        auth_type:
          type: string
          enum: ['none', 'basic', 'token']
        username:
          type: string
        password:
          type: string
        token:
          type: string
        enabled:
          type: boolean
      required:
        - id
        - url
