name: OCPP Proxy
version: '0.1.2'
slug: ocpp-proxy
description: 'OCPP 1.6 JSON WebSocket proxy for EV charger sharing'
homeassistant_api: true
arch:
  - amd64
  - armv7
  - aarch64
  - armhf
startup: services
boot: auto
options:
  allow_shared_charging: true
  preferred_provider: ''
  blocked_providers: []
  allowed_providers: []
  presence_sensor: ''
  override_input_boolean: ''
  rate_limit_seconds: 10
  ocpp_services: []
schema:
  allow_shared_charging: bool
  preferred_provider: str?
  blocked_providers:
    - str
  allowed_providers:
    - str
  presence_sensor: str?
  override_input_boolean: str?
  rate_limit_seconds: int(1,300)
  ocpp_services:
    - id: str
      url: str
      auth_type: list(none|basic|token)?
      username: str?
      password: str?
      token: str?
      enabled: bool?
